FROM worzeel/tmux:golang

RUN apk update \
    && apk upgrade \
    && apk add vim git \
    && git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go \
    && rm -rf /var/cache/apk/*

COPY base/.vim /root/.vim
COPY base/.vimrc /root/.vimrc
